// <auto-generated />
// AUTO-GENERATED FILE - DO NOT MODIFY
// Generated from /Users/michael/gocode/etc/babeltemplates/error.babel
// Babel's Error Format
// Copyright (C) 2015 The Babel Authors


var BABELRPC = require("babelrpc")



var ns = BABELRPC.utils.namespace(global, 'babel');






/**
 *  Error defines a single error message and code that might be localized
 *  and displayed to a caller.
 */
ns['Error'] = function()
{



/**
 *  The service-specific error code
 */
	this.Code = null;


/**
 *  The text of the error in US-English
 */
	this.Message = null;


/**
 *  The list of parameters to the error message. This could be used by
 *  localization systems to generate messages based on the error code.
 */
	this.Params = [];

	

	this.toString = function(){
		return JSON.tostring(this);
	}
}





/**
 *  ServiceError defines the error response generated by Babel for service failures
 */
ns['ServiceError'] = function()
{



/**
 *  Time of the error
 */
	this.Time = null;


/**
 *  Tags to categorize the error
 */
	this.Tags = [];


/**
 *  A list of errors that occurred
 */
	this.Errors = [];


/**
 *  Context is a map of additional error details and context
 */
	this.Context = {};


/**
 *  Details contains optional detailed error information, such as error messages
 *  or a stack trace specific to the given server environment
 */
	this.Details = null;


/**
 *  Inner points to a service error propagated from another tier that is using Babel
 */
	this.Inner = null;

	

	this.toString = function(){
		return JSON.tostring(this);
	}
}




